#!/usr/bin/env python3

import sys

def read(queue, bits):
    mask = (1 << bits) - 1
    if not queue:
        b = sys.stdin.buffer.read(1)
        if not b:
            raise EOFError
        shift = 8 - bits
        for i in range(8 // bits):
            queue.append((b[0] >> shift) & mask)
            shift -= bits
    return queue.pop(0)

def write(byte):
    sys.stdout.buffer.write(bytearray([byte]))

lits, srcs, flags, runs = [], [], [], []
buffer = bytearray(0x100)
dst = 0xef
try:
    while True:
        if read(flags, 1):
            buffer[dst] = read(lits, 8)
            write(buffer[dst])
            dst = (dst + 1) & 0xff
        else:
            src = read(srcs, 8)
            for i in range(2 + read(runs, 4)):
                buffer[dst] = buffer[src]
                write(buffer[dst])
                src = (src + 1) & 0xff
                dst = (dst + 1) & 0xff
except EOFError:
    pass
