; Disassembly of "Nectaris GB (Japan) (SGB Enhanced).gb"

def OWN equ $00
def FOE equ $80

def FACTORY equ $20

def YAMA equ $00
def FALCO equ $01
def JAVI equ $02
def HUNTER equ $03
def GRIZZLY equ $04
def DILLO equ $05
def BISON equ $06
def SLAGGER equ $07
def MONSTER equ $08
def GIANT equ $09
def LENET equ $0a
def NASHORN equ $0b
def ESTOL equ $0c
def RABBIT equ $0d
def LYNX equ $0e
def SEEKER equ $0f
def HAWKEYE equ $10
def RHINO equ $11
def MUNKS equ $12
def DARBEK equ $13
def DRAPER equ $14
def MULE equ $15
def PELICAN equ $16

NEWCHARMAP Map

CHARMAP " ", $00  ; open
CHARMAP "+", $01  ; road
CHARMAP "o", $02  ; hill
CHARMAP "~", $03  ; desert
CHARMAP "#", $04  ; valley
CHARMAP "M", $05  ; mountain
CHARMAP "*", $06  ; bridge
CHARMAP "8", $08  ; own base
CHARMAP "P", $0a  ; foe base
CHARMAP "b", $0b  ; own factory
CHARMAP "F", $0c  ; factory
CHARMAP "d", $0d  ; foe factory

CHARMAP "f", $0f
CHARMAP "g", $77
CHARMAP "h", $78
CHARMAP "i", $79
CHARMAP "j", $80
CHARMAP "k", $81
CHARMAP "l", $82
CHARMAP "q", $9c
CHARMAP "u", $da
CHARMAP "v", $20
CHARMAP "w", $bc
CHARMAP "x", $cd
CHARMAP "y", $13
CHARMAP "z", $e4
